### ISSUE TITLE
Tests failing or not running on master

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/unitaryhackdev#73]
**Describe the bug**
Tests failing or not running on master.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by natestemen** [comment]
This seems to be due to two reasons:
- The [`frontmatter`](https://pypi.org/project/python-frontmatter/) package doesn't like that [one of the issue](https://github.com/zapatacomputing/orquestra-core/issues/11) names begins with a backtick. This causes the error we see in the failing GitHub action run.
- Upon renaming the offending issue name in the [markdown file](https://github.com/unitaryfund/unitaryhackdev/blob/a10b3675d904a4702c007f0362532f0f46eaa2b2/projects/orquestra_core.md), the script runs further until it gets rate-limited by the GitHub API.

These can be remedied by changing the title of the offending issue, along with adding some delay between requests in the [`scrape_github.py`](https://github.com/unitaryfund/unitaryhackdev/blob/a10b3675d904a4702c007f0362532f0f46eaa2b2/_data/scrape_github.py) file. That said, the github API seems to have a limit of 60 requests per some time limit, which I'm not sure the duration of:
```
curl -I https://api.github.com/users/octocat
HTTP/2 200 
server: GitHub.com
date: Fri, 03 Jun 2022 05:09:42 GMT
...
x-ratelimit-limit: 60
x-ratelimit-remaining: 59
x-ratelimit-reset: 1654236582
x-ratelimit-resource: core
x-ratelimit-used: 1
```

**Comment by natestemen** [comment]
cc @crazy4pi314. Do you have a sense if the failing builds mean the data is only partially being updated?

**Comment by natestemen** [comment]
Looks as though https://github.com/unitaryfund/unitaryhackdev/pull/88 fixed the issue and the builds are passing.
